@startuml Cdastro de Motorista

left to right direction

actor RH
rectangle "Cadastro de Motorista" as CadMot {
  usecase "Preencher as informações básicas" as cadMot_Info
  usecase "Validar CNH" as cadMot_ValiCNH
  usecase "Mostrar mensagem: CNH inválida" as cadMot_InvaCNH
  usecase "Gerar ID para motorista" as cadMot_ID
  usecase "Validar ID único" as cadMot_ValiID
  usecase "Mostrar mensagem: ID inválido, já está em uso" as cadMot_InvaID
}

RH --> cadMot_Info
cadMot_Info .down.> cadMot_ValiCNH: <<include>>
cadMot_ValiCNH <.. cadMot_ID: <<extend>>
cadMot_ValiCNH <.up. cadMot_InvaCNH: <<extend>>
cadMot_ID .down.> cadMot_ValiID: <<include>>
cadMot_ValiID <.up. cadMot_InvaID: <<extend>>

@enduml
