@startuml Pareamento de Rotas

left to right direction

actor Sistema
actor Motorista
actor Passageiro

rectangle "Pareamento de Rotas" {
    usecase "Coletar informações de rotas cadastradas" as pareRotas_ColetInfo
    usecase "Comparar horários e destinos" as pareRotas_CompHorDest
    usecase "Sugerir pareamentos compatíveis" as pareRotas_SugPare
}

Sistema --> pareRotas_ColetInfo
pareRotas_ColetInfo ..> pareRotas_CompHorDest: <<include>>
pareRotas_CompHorDest ..> pareRotas_SugPare: <<include>>
pareRotas_SugPare --> Motorista
pareRotas_SugPare --> Passageiro

@enduml
