@startuml Principal

!include cadastroMotorista.puml
!include cadastroVeiculo.puml
!include cadastroRota.puml
!include reserveAssentos.puml
!include solicitacaoReembolso.puml
!include alertarAutomaticos.puml
!include pareamentoRotas.puml

@enduml